package ofdfielddefine

var Define = map[string]interface{}{
	"acctmanfee":                             map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "null"},
	"instappsubsamnt":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人追加认购金额"},
	"instappsubsvol":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人追加认购份数"},
	"address":                                map[string]interface{}{"type": "C", "size": 120, "comment": "通讯地址"},
	"instrepridcode":                         map[string]interface{}{"type": "C", "size": 30, "comment": "法人代表身份证件代码"},
	"instrepridtype":                         map[string]interface{}{"type": "C", "size": 1, "comment": "法人代表证件类型"},
	"instreprname":                           map[string]interface{}{"type": "C", "size": 20, "comment": "法人代表姓名"},
	"appsheetserialno":                       map[string]interface{}{"type": "A", "size": 24, "comment": "申请单编号"},
	"totalsubsamnt":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购总金额"},
	"totalaccptdsubsvol":                     map[string]interface{}{"type": "N", "size": 10, "scale": 0, "comment": "成功申购总笔数"},
	"totalsubscharge":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购手续费总金额"},
	"totalsubsvol":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购总份数"},
	"availablevol":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "持有人可用基金份数"},
	"issuetype":                              map[string]interface{}{"type": "C", "size": 1, "comment": "基金发行方式"},
	"amntreinbursed":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "退回金额"},
	"backendload":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "每笔交易后端收费"},
	"acctbalanceinindividualdistribut":       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "持有人在单个销售机构的基金份数"},
	"totalvolofdistributorinta":              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金总份数（含冻结）"},
	"cctnooffminclearingagency":              map[string]interface{}{"type": "C", "size": 28, "comment": "基金管理人在资金清算机构的交收账号"},
	"cctnameoffminclearingagency":            map[string]interface{}{"type": "C", "size": 60, "comment": "基金管理人在资金清算机构的交收账户名"},
	"clearingagencycode":                     map[string]interface{}{"type": "A", "size": 9, "comment": "基金资金清算机构代码"},
	"basisforcalculatingdividend":            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "红利/红利再投资基数"},
	"investorsbirthday":                      map[string]interface{}{"type": "A", "size": 8, "comment": "投资人出生日期"},
	"defdividendmethod":                      map[string]interface{}{"type": "A", "size": 1, "comment": "默认分红方式"},
	"discountrateofcommission":               map[string]interface{}{"type": "N", "size": 5, "scale": 4, "comment": "销售佣金折扣率"},
	"certificatetype":                        map[string]interface{}{"type": "C", "size": 1, "comment": "证件类型"},
	"depositacct":                            map[string]interface{}{"type": "C", "size": 19, "comment": "投资人在销售人处用于交易的资金账号"},
	"regioncode":                             map[string]interface{}{"type": "A", "size": 4, "comment": "交易所在地区编号"},
	"transferdatefromcustodian":              map[string]interface{}{"type": "A", "size": 8, "comment": "清算资金自托管人处划出日期"},
	"transferdatethroughclearingagenc":       map[string]interface{}{"type": "A", "size": 8, "comment": "清算资金经清算人划出日期"},
	"transactioncfmdate":                     map[string]interface{}{"type": "A", "size": 8, "comment": "交易确认日期"},
	"codeoftargetfund":                       map[string]interface{}{"type": "A", "size": 6, "comment": "转换时的目标基金代码"},
	"minamountbyinst":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人首次认购最低金额"},
	"minvolbyinst":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人首次认购最低份数"},
	"currencytype":                           map[string]interface{}{"type": "A", "size": 3, "comment": "结算币种"},
	"custodiancode":                          map[string]interface{}{"type": "A", "size": 3, "comment": "托管人代码"},
	"amountofperiodicsubs":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "定时定额申购的金额"},
	"dateofperiodicsubs":                     map[string]interface{}{"type": "A", "size": 8, "comment": "定时定额申购日期"},
	"volofdividendforreinvestment":           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金账户红利再投资基金份数"},
	"dividentdate":                           map[string]interface{}{"type": "A", "size": 8, "comment": "分红日/发放日"},
	"dividendamount":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金账户红利资金"},
	"totaldividendamount":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金红利总额"},
	"dividendorshare":                        map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"xrdate":                                 map[string]interface{}{"type": "A", "size": 8, "comment": "除权日"},
	"downloaddate":                           map[string]interface{}{"type": "A", "size": 8, "comment": "交易数据下传日期"},
	"educationlevel":                         map[string]interface{}{"type": "C", "size": 3, "comment": "投资人学历"},
	"emailaddress":                           map[string]interface{}{"type": "C", "size": 40, "comment": "投资人E-MAIL地址"},
	"totaldividendindeed":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金实发红利总金额"},
	"faxno":                                  map[string]interface{}{"type": "C", "size": 24, "comment": "投资人传真号码"},
	"charge":                                 map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "手续费"},
	"agencyfee":                              map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "代理费"},
	"chargerate":                             map[string]interface{}{"type": "N", "size": 6, "scale": 4, "comment": "手续费率"},
	"totaltransfee":                          map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "交易确认费用合计"},
	"totalfeefordividend":                    map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "分红费用合计"},
	"announcementno":                         map[string]interface{}{"type": "C", "size": 13, "comment": "公告文件号"},
	"freezingdeadline":                       map[string]interface{}{"type": "A", "size": 8, "comment": "冻结截止日期"},
	"totalfrozenvol":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金冻结总份数"},
	"frozencause":                            map[string]interface{}{"type": "A", "size": 1, "comment": "冻结原因"},
	"frontendfee":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "每笔交易前端收费"},
	"confirmedvol":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金账户交易确认份数"},
	"fundname":                               map[string]interface{}{"type": "C", "size": 40, "comment": "基金名称"},
	"confirmedamount":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "每笔交易确认金额"},
	"vocationcode":                           map[string]interface{}{"type": "C", "size": 3, "comment": "投资人职业代码"},
	"totalfundvol":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金总份数"},
	"fundcode":                               map[string]interface{}{"type": "C", "size": 6, "comment": "基金代码"},
	"fundstatus":                             map[string]interface{}{"type": "C", "size": 1, "comment": "基金状态"},
	"hometelno":                              map[string]interface{}{"type": "C", "size": 22, "comment": "投资人住址电话"},
	"maxredemptionvol":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金最高赎回份数"},
	"minaccountbalance":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金最低持有份数"},
	"certificateno":                          map[string]interface{}{"type": "C", "size": 30, "comment": "投资人证件号码"},
	"annualincome":                           map[string]interface{}{"type": "N", "size": 8, "scale": 0, "comment": "投资人年收入"},
	"announcementdate":                       map[string]interface{}{"type": "A", "size": 8, "comment": "公告日期格式为：YYYYMMDD"},
	"announcementtype":                       map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"interest":                               map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "基金账户利息金额"},
	"backamountbyinvalid":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "因为无效而划回投资人的资金"},
	"ipostartdate":                           map[string]interface{}{"type": "A", "size": 8, "comment": "基金募集开始日期"},
	"ipoenddate":                             map[string]interface{}{"type": "A", "size": 8, "comment": "基金募集结束日期"},
	"largeredemptionflag":                    map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"lengthofannouncement":                   map[string]interface{}{"type": "N", "size": 10, "scale": 0, "comment": "公告内容长度"},
	"fundmanagercode":                        map[string]interface{}{"type": "C", "size": 3, "comment": "基金管理人"},
	"mobiletelno":                            map[string]interface{}{"type": "C", "size": 24, "comment": "投资人手机号码"},
	"multiacctflag":                          map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"investorname":                           map[string]interface{}{"type": "C", "size": 120, "comment": "投资人户名"},
	"nav":                                    map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "基金单位净值"},
	"branchcode":                             map[string]interface{}{"type": "C", "size": 9, "comment": "网点号码"},
	"officetelno":                            map[string]interface{}{"type": "C", "size": 22, "comment": "投资人单位电话号码"},
	"originalserialno":                       map[string]interface{}{"type": "A", "size": 20, "comment": "TA的原确认流水号"},
	"originalappsheetno":                     map[string]interface{}{"type": "A", "size": 24, "comment": "原申请单编号"},
	"originalsubsdate":                       map[string]interface{}{"type": "A", "size": 8, "comment": "原申购日期"},
	"transactiondate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "交易发生日期"},
	"transactiontime":                        map[string]interface{}{"type": "A", "size": 6, "comment": "交易发生时间"},
	"otherfee1":                              map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "其他费用1"},
	"otherfee2":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "其他费用2"},
	"otherfee3":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "其他费用3"},
	"targetdistributorcode":                  map[string]interface{}{"type": "C", "size": 9, "comment": "对方销售人代码"},
	"individualorinstitution":                map[string]interface{}{"type": "A", "size": 1, "comment": "投资者类别"},
	"indiappsubsvol":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人追加认购份数"},
	"indiappsubsamount":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人追加认购金额"},
	"postcode":                               map[string]interface{}{"type": "A", "size": 6, "comment": "投资人邮政编码"},
	"redemptiondateinadvance":                map[string]interface{}{"type": "A", "size": 8, "comment": "预约赎回日期"},
	"ipoprice":                               map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "发行价格"},
	"minsubsvolbyindi":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人首次认购最低份数"},
	"minsubsamountbyindi":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人首次认购最低金额"},
	"transactorcertno":                       map[string]interface{}{"type": "C", "size": 30, "comment": "经办人证件号码"},
	"transactorcerttype":                     map[string]interface{}{"type": "C", "size": 1, "comment": "经办人证件类型"},
	"transactorname":                         map[string]interface{}{"type": "C", "size": 20, "comment": "经办人姓名"},
	"totalredemptionamount":                  map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金赎回总金额"},
	"totaltransactionofsuccessfulrede":       map[string]interface{}{"type": "N", "size": 10, "scale": 0, "comment": "成功赎回总笔数"},
	"totalfeeofredemption":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回手续费总金额"},
	"volonregistraiondate":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "权益登记日基金账户份数"},
	"registrationdate":                       map[string]interface{}{"type": "A", "size": 8, "comment": "权益登记日期"},
	"registrarcode":                          map[string]interface{}{"type": "C", "size": 2, "comment": "注册登记人代码"},
	"registrationfee":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "注册登记费"},
	"totalreinvestmentdividend":              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "红利自动再投资总金额"},
	"backamountbyexcess":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "因为剩余而划回投资人的资金"},
	"totalredemptionvol":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回总份数"},
	"returncode":                             map[string]interface{}{"type": "A", "size": 4, "comment": "交易处理返回代码取值见附录B"},
	"transactionaccountid":                   map[string]interface{}{"type": "A", "size": 17, "comment": "投资人基金交易账号"},
	"distributorcode":                        map[string]interface{}{"type": "C", "size": 9, "comment": "销售人代码"},
	"accountabbr":                            map[string]interface{}{"type": "C", "size": 12, "comment": "投资人户名简称"},
	"dividendratio":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "红利比例"},
	"confidentialdocumentcode":               map[string]interface{}{"type": "C", "size": 8, "comment": "密函编号"},
	"documentsenddate":                       map[string]interface{}{"type": "A", "size": 8, "comment": "文件发送日期"},
	"sex":                                    map[string]interface{}{"type": "A", "size": 1, "comment": "性别"},
	"shsecuritiesaccountid":                  map[string]interface{}{"type": "C", "size": 10, "comment": "上交所证券账号"},
	"szsecuritiesaccountid":                  map[string]interface{}{"type": "C", "size": 10, "comment": "深交所证券账号"},
	"fundsize":                               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金规模"},
	"fundsponsor":                            map[string]interface{}{"type": "A", "size": 3, "comment": "基金发起人"},
	"announcementtitle":                      map[string]interface{}{"type": "C", "size": 100, "comment": "公告标题"},
	"applicationvol":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申请基金份数"},
	"tradingprice":                           map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "交易价格"},
	"applicationamount":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申请金额"},
	"businesscode":                           map[string]interface{}{"type": "A", "size": 3, "comment": "业务代码"},
	"taaccountid":                            map[string]interface{}{"type": "A", "size": 12, "comment": "投资人基金账号"},
	"taserialno":                             map[string]interface{}{"type": "A", "size": 20, "comment": "TA确认交易流水号"},
	"stampduty":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "印花税"},
	"tax":                                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "税金"},
	"telno":                                  map[string]interface{}{"type": "C", "size": 22, "comment": "投资人电话号码"},
	"targetbranchcode":                       map[string]interface{}{"type": "C", "size": 9, "comment": "对方网点号"},
	"targettransactionaccountid":             map[string]interface{}{"type": "A", "size": 17, "comment": "对方销售人处投资人基金交易账号"},
	"aggregationoftransactionbybusine":       map[string]interface{}{"type": "N", "size": 8, "scale": 0, "comment": "每种业务笔数汇总"},
	"aggregationdate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "汇总日期"},
	"totalvol":                               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金份数汇总"},
	"totalamount":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金金额汇总"},
	"targettaaccountid":                      map[string]interface{}{"type": "C", "size": 12, "comment": "对方基金账号"},
	"trailcommission":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "尾随佣金"},
	"updatedate":                             map[string]interface{}{"type": "A", "size": 8, "comment": "基金净值日期"},
	"validperiod":                            map[string]interface{}{"type": "N", "size": 2, "scale": 0, "comment": "交易申请有效天数"},
	"facevalue":                              map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "基金面值"},
	"targetregioncode":                       map[string]interface{}{"type": "A", "size": 4, "comment": "对方所在地区编号"},
	"totalfailingvol":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "失败份数汇总"},
	"totalsuccessfulvol":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "成功份数汇总"},
	"dividendperunit":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "单位基金分红金额（含税）"},
	"interesttax":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "利息税"},
	"fundvolbalance":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金份数余额"},
	"beginallotno":                           map[string]interface{}{"type": "N", "size": 12, "scale": 0, "comment": "配号开始号"},
	"endallotno":                             map[string]interface{}{"type": "N", "size": 12, "scale": 0, "comment": "配号结束号"},
	"totalallotno":                           map[string]interface{}{"type": "N", "size": 12, "scale": 0, "comment": "配号总数"},
	"cfmvoloftargetfund":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "目标基金的确认份数"},
	"targetnav":                              map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "目标基金的单位净值"},
	"targetfundprice":                        map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "目标基金的价格"},
	"tradingmethod":                          map[string]interface{}{"type": "C", "size": 8, "comment": "使用的交易手段"},
	"contractno":                             map[string]interface{}{"type": "A", "size": 20, "comment": "合约编号"},
	"selfhelp":                               map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"minorflag":                              map[string]interface{}{"type": "C", "size": 1, "comment": "未成年人标志"},
	"delivertype":                            map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"transactoridtype":                       map[string]interface{}{"type": "C", "size": 1, "comment": "经办人识别方式"},
	"accountcardid":                          map[string]interface{}{"type": "C", "size": 8, "comment": "基金账户卡的凭证号"},
	"totalfrontendfee":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "交易前端收费总额"},
	"totalbackendload":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "交易后端收费总额"},
	"totalfailingamount":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "失败金额汇总"},
	"totalsuccessfulamount":                  map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "成功金额汇总"},
	"transferdirection":                      map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"businessfinishflag":                     map[string]interface{}{"type": "C", "size": 1, "comment": "业务过程完全结束标识"},
	"totalfailingdealingnum":                 map[string]interface{}{"type": "N", "size": 6, "scale": 0, "comment": "失败交易笔数"},
	"totalsuccessfuldealingnum":              map[string]interface{}{"type": "N", "size": 6, "scale": 0, "comment": "成功交易笔数"},
	"convertstatus":                          map[string]interface{}{"type": "C", "size": 1, "comment": "基金转换状态"},
	"acctnameofinvestorinclearingagency":     map[string]interface{}{"type": "C", "size": 60, "comment": "投资人收款银行账户户名"},
	"acctnoofinvestorinclearingagency":       map[string]interface{}{"type": "C", "size": 28, "comment": "投资人收款银行账户账号"},
	"clearingagency":                         map[string]interface{}{"type": "A", "size": 9, "comment": "投资人收款银行账户开户行"},
	"unfrozenbalance":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "解冻红利金额"},
	"businessorganiger":                      map[string]interface{}{"type": "C", "size": 3, "comment": "业务发起人代码"},
	"accounttype":                            map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"frozenbalance":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "冻结金额"},
	"frozenshares":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "冻结红利再投资份数"},
	"totalfare":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "交易费用汇总"},
	"vastredeemflag":                         map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"termofperiodicsubs":                     map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": "定时定额申购期限"},
	"futurebuydate":                          map[string]interface{}{"type": "A", "size": 8, "comment": "指定申购日期"},
	"ratefee":                                map[string]interface{}{"type": "N", "size": 9, "scale": 8, "comment": "费率"},
	"minfee":                                 map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "最少收费"},
	"daysredemptioninadvance":                map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": "预约赎回工作日天数"},
	"maxsubsvolbyindi":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人最高认购份数"},
	"maxsubsamountbyindi":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人最高认购金额"},
	"maxsubsvolbyinst":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人最高认购份数"},
	"maxsubsamountbyinst":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人最高认购金额"},
	"unitsubsvolbyindi":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人认购份数单位"},
	"unitsubsamountbyindi":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人认购金额单位"},
	"unitsubsvolbyinst":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人认购份数单位"},
	"unitsubsamountbyinst":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人认购金额单位"},
	"minbidsamountbyindi":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人首次申购最低金额"},
	"minbidsamountbyinst":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人首次申购最低金额"},
	"minappbidsamountbyindi":                 map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人追加申购最低金额"},
	"minappbidsamountbyinst":                 map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人追加申购最低金额"},
	"minredemptionvol":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金最少赎回份数"},
	"mininterconvertvol":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "最低基金转换份数"},
	"issuetypebyindi":                        map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"issuetypebyinst":                        map[string]interface{}{"type": "C", "size": 1, "comment": "机构发行方式"},
	"substype":                               map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"collectfeetype":                         map[string]interface{}{"type": "C", "size": 1, "comment": "交易费收取方式"},
	"nexttradedate":                          map[string]interface{}{"type": "A", "size": 8, "comment": "下一交易日"},
	"salernettreceivableamount":              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人净收结算金额"},
	"salernetpayableamount":                  map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人净付结算金额"},
	"salertotalfee":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人收取费用总额"},
	"salerbidfee":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人收取申购费用"},
	"fundtotalfee":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回费用总额（扣除保留在基金资产部分）"},
	"raisetotalamount":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "认购资金总额"},
	"accumulativetotalraiseamount":           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "累计认购资金总额"},
	"raiseinterest":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "认购期间利息"},
	"salerraisefee":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人认购费"},
	"conversion inamount":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "转入款"},
	"converting to amount":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "转出款"},
	"saler exchange fee":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人转换费"},
	"bid tax":                                map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购印花税"},
	"redemption tax":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回印花税"},
	"individualcapitalgaintax":               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "分红个人利得所得税"},
	"institutecapital gaintax":               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "分红机构利得所得税"},
	"individual income tax":                  map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "分红个人增值所得税"},
	"institute income tax":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "分红机构增值所得税"},
	"salerreinvestmentfee":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "销售人再投资费"},
	"subfeeretta":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购归注册登记人所得费用"},
	"redemfeeretta":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回归注册登记人所得费用"},
	"totaltransinamount":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换入总金额"},
	"totalfeeoftransinamount":                map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换入手续费总金额"},
	"totaltransinvol":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换入总份数"},
	"totaltransoutamount":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换出总金额"},
	"totalfeeoftransoutamount":               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换出手续费总金额"},
	"totaltransoutvol":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换出总份数"},
	"bidtrade":                               map[string]interface{}{"type": "N", "size": 13, "scale": 0, "comment": "成功申购总户数"},
	"redeemtrade":                            map[string]interface{}{"type": "N", "size": 13, "scale": 0, "comment": "成功赎回总户数"},
	"freezetotal":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "冻结总份数"},
	"managercode":                            map[string]interface{}{"type": "A", "size": 3, "comment": "管理人代码"},
	"netbidtotalamount":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购成功资金总额（不含费用，不含税）"},
	"netredeemtotalamount":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回成功资金总额（不含费用，不含税）"},
	"creditdebit":                            map[string]interface{}{"type": "N", "size": 1, "scale": 0, "comment": "1-贷方"},
	"redemptionfee":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回费"},
	"netsettlement":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "资金清算净额全额交收可以用作实际清算额"},
	"specification":                          map[string]interface{}{"type": "C", "size": 60, "comment": "摘要/说明"},
	"transferfee":                            map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "过户费"},
	"fromtaflag":                             map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"frozenmethod":                           map[string]interface{}{"type": "A", "size": 1, "comment": "冻结方式"},
	"originalappdate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "原申请日期"},
	"totalbackendloadvol":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "交易后端收费总份数"},
	"shareclass":                             map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"originalcfmdate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "TA的原确认日期"},
	"redemptioninadvanceflag":                map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"redemptionreason":                       map[string]interface{}{"type": "A", "size": 1, "comment": "强行赎回原因"},
	"detailflag":                             map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"deliverway":                             map[string]interface{}{"type": "C", "size": 8, "comment": "对账单寄送方式"},
	"volumebyinterest":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "利息产生的基金份数"},
	"valueline":                              map[string]interface{}{"type": "N", "size": 7, "scale": 2, "comment": "产品价值线数值"},
	"accountstatus":                          map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"begindateofperiodicsubs":                map[string]interface{}{"type": "A", "size": 8, "comment": "定时定额申购起始日期"},
	"enddateofperiodicsubs":                  map[string]interface{}{"type": "A", "size": 8, "comment": "定时定额申购终止日期"},
	"senddayofperiodicsubs":                  map[string]interface{}{"type": "N", "size": 2, "scale": 0, "comment": "定时定额申购每周期发送日"},
	"totalvolumeofreinvestmentdividen":       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "红利再投资份额总额"},
	"accumulativenav":                        map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "累计基金单位净值"},
	"shareregisterdate":                      map[string]interface{}{"type": "A", "size": 8, "comment": "份额注册日期"},
	"largebuyflag":                           map[string]interface{}{"type": "A", "size": 1, "comment": ""},
	"feecalculator":                          map[string]interface{}{"type": "A", "size": 1, "comment": "计费人"},
	"indiacctcfmrate":                        map[string]interface{}{"type": "N", "size": 5, "scale": 4, "comment": "个人账户确认比例"},
	"instacctcfmrate":                        map[string]interface{}{"type": "N", "size": 5, "scale": 4, "comment": "机构账户确认比例"},
	"genacctcfmrate":                         map[string]interface{}{"type": "N", "size": 5, "scale": 4, "comment": "综合账户确认比例"},
	"varietycodeofperiodicsubs":              map[string]interface{}{"type": "C", "size": 5, "comment": "定时定额品种代码"},
	"serialnoofperiodicsubs":                 map[string]interface{}{"type": "C", "size": 5, "comment": "定时定额申购序号"},
	"corpname":                               map[string]interface{}{"type": "C", "size": 40, "comment": "工作单位名称"},
	"refundamount":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "退款金额"},
	"securitiesaccountid":                    map[string]interface{}{"type": "C", "size": 10, "comment": "证券账号"},
	"salepercent":                            map[string]interface{}{"type": "N", "size": 8, "scale": 5, "comment": "配售比例"},
	"certvaliddate":                          map[string]interface{}{"type": "A", "size": 8, "comment": "证件有效日期"},
	"insttrancertvaliddate":                  map[string]interface{}{"type": "A", "size": 8, "comment": "机构经办人身份证件有效日期"},
	"instreprcertvaliddate":                  map[string]interface{}{"type": "A", "size": 8, "comment": "机构法人身份证件有效日期"},
	"clientriskrate":                         map[string]interface{}{"type": "C", "size": 1, "comment": "客户风险等级"},
	"instreprmanagerange":                    map[string]interface{}{"type": "C", "size": 2, "comment": ""},
	"controlholder":                          map[string]interface{}{"type": "C", "size": 80, "comment": "控股股东"},
	"actualcontroller":                       map[string]interface{}{"type": "C", "size": 80, "comment": "实际控制人"},
	"marriagestatus":                         map[string]interface{}{"type": "C", "size": 1, "comment": "1-已婚"},
	"familynum":                              map[string]interface{}{"type": "N", "size": 2, "scale": 0, "comment": "家庭人口数"},
	"penates":                                map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "家庭资产"},
	"mediahobby":                             map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"customerno":                             map[string]interface{}{"type": "C", "size": 12, "comment": "TA客户编号"},
	"rationprotocolno":                       map[string]interface{}{"type": "C", "size": 20, "comment": "定期定额协议号"},
	"rationtype":                             map[string]interface{}{"type": "C", "size": 1, "comment": "定期定额种类"},
	"breachfee":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "违约金"},
	"salespromotion":                         map[string]interface{}{"type": "C", "size": 3, "comment": "促销活动代码"},
	"acceptmethod":                           map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"forceredemptiontype":                    map[string]interface{}{"type": "C", "size": 1, "comment": "强制赎回类型"},
	"allowbreachredempt":                     map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"punishfee":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "惩罚性费用"},
	"breachfeebacktofund":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "违约金归基金资产金额"},
	"futuresubscribedate":                    map[string]interface{}{"type": "A", "size": 8, "comment": "指定认购日期"},
	"totaldivident":                          map[string]interface{}{"type": "N", "size": 8, "scale": 5, "comment": "累积单位分红"},
	"errordetail":                            map[string]interface{}{"type": "C", "size": 60, "comment": "出错详细信息"},
	"fundtype":                               map[string]interface{}{"type": "C", "size": 2, "comment": ""},
	"pointstype":                             map[string]interface{}{"type": "C", "size": 1, "comment": "积分类型"},
	"points":                                 map[string]interface{}{"type": "N", "size": 15, "scale": 2, "comment": "积分值"},
	"fundcorpcode":                           map[string]interface{}{"type": "C", "size": 8, "comment": "基金公司代码"},
	"fundservertel":                          map[string]interface{}{"type": "C", "size": 30, "comment": "基金公司客服电话"},
	"fundinternetaddress":                    map[string]interface{}{"type": "C", "size": 40, "comment": "基金公司网站网址"},
	"pointsstatus":                           map[string]interface{}{"type": "C", "size": 1, "comment": "1-作废"},
	"announcflag":                            map[string]interface{}{"type": "C", "size": 1, "comment": "1-不公告"},
	"transferpermitflag":                     map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"instaccount":                            map[string]interface{}{"type": "C", "size": 30, "comment": "销售人结算法人资金帐号"},
	"capitaltype":                            map[string]interface{}{"type": "C", "size": 3, "comment": "资金类型"},
	"receorpayflag":                          map[string]interface{}{"type": "C", "size": 1, "comment": "收付标志"},
	"calculatedate":                          map[string]interface{}{"type": "A", "size": 8, "comment": "清算日期"},
	"paydate":                                map[string]interface{}{"type": "A", "size": 8, "comment": "交收日期"},
	"seatcode":                               map[string]interface{}{"type": "C", "size": 6, "comment": "席位代码"},
	"institutiontype":                        map[string]interface{}{"type": "C", "size": 1, "comment": "机构类型"},
	"distributorname":                        map[string]interface{}{"type": "C", "size": 80, "comment": "销售人名称"},
	"takeincomeflag":                         map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"purposeofpesubs":                        map[string]interface{}{"type": "C", "size": 40, "comment": "定投目的"},
	"frequencyofpesubs":                      map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": ""},
	"batchnumofpesubs":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "定投期数"},
	"fundtypename":                           map[string]interface{}{"type": "C", "size": 30, "comment": "基金类型名称"},
	"registrarname":                          map[string]interface{}{"type": "C", "size": 40, "comment": "注册登记人名称"},
	"fundmanagername":                        map[string]interface{}{"type": "C", "size": 40, "comment": "基金管理人名称"},
	"englishfirstname":                       map[string]interface{}{"type": "C", "size": 20, "comment": "投资人英文名"},
	"englishfamliyname":                      map[string]interface{}{"type": "C", "size": 20, "comment": "投资人英文姓"},
	"vocation":                               map[string]interface{}{"type": "C", "size": 4, "comment": "行业"},
	"corpoproperty":                          map[string]interface{}{"type": "C", "size": 2, "comment": "企业性质"},
	"staffnum":                               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "员工人数"},
	"hobbytype":                              map[string]interface{}{"type": "C", "size": 2, "comment": "兴趣爱好类型"},
	"province":                               map[string]interface{}{"type": "C", "size": 6, "comment": "省/直辖市"},
	"city":                                   map[string]interface{}{"type": "C", "size": 6, "comment": "市"},
	"county":                                 map[string]interface{}{"type": "C", "size": 6, "comment": "县/区"},
	"commendperson":                          map[string]interface{}{"type": "C", "size": 40, "comment": "推荐人"},
	"commendpersontype":                      map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"capitalmode":                            map[string]interface{}{"type": "C", "size": 2, "comment": "资金方式"},
	"detailcapticalmode":                     map[string]interface{}{"type": "C", "size": 2, "comment": "明细资金方式"},
	"backenloaddiscount":                     map[string]interface{}{"type": "N", "size": 5, "scale": 4, "comment": "补差费折扣率"},
	"combinenum":                             map[string]interface{}{"type": "C", "size": 6, "comment": "组合编号"},
	"alternationdate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "最后更新日"},
	"targetdistributortype":                  map[string]interface{}{"type": "C", "size": 1, "comment": "对方销售人类型"},
	"xrvalue":                                map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "单位除权值"},
	"xrvalueflag":                            map[string]interface{}{"type": "C", "size": 1, "comment": "1-负"},
	"xrtype":                                 map[string]interface{}{"type": "C", "size": 1, "comment": "1-净值调整"},
	"dividendtype":                           map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"sequenceno":                             map[string]interface{}{"type": "A", "size": 20, "comment": "序号"},
	"operatedate":                            map[string]interface{}{"type": "A", "size": 8, "comment": "生效日期"},
	"vollowerlimit":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "份额下限"},
	"volupperlimit":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "份额上限"},
	"amountlowerlimit":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "金额下限"},
	"amountupperlimit":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "金额上限"},
	"dayslowerlimit":                         map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": "天数下限"},
	"daysupperlimit":                         map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": "天数上限"},
	"maxfee":                                 map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "最高费用"},
	"getfeeratemethod":                       map[string]interface{}{"type": "C", "size": 1, "comment": "3-按份额"},
	"feerateflag":                            map[string]interface{}{"type": "C", "size": 1, "comment": "1-相对费率"},
	"fundnameabbr":                           map[string]interface{}{"type": "C", "size": 20, "comment": "基金简称"},
	"isguaranteedfund":                       map[string]interface{}{"type": "C", "size": 1, "comment": "1-是"},
	"isloffund":                              map[string]interface{}{"type": "C", "size": 1, "comment": "1-是"},
	"isqdiifund":                             map[string]interface{}{"type": "C", "size": 1, "comment": "1-是"},
	"isetffund":                              map[string]interface{}{"type": "C", "size": 1, "comment": "1-是"},
	"redeemfeebackratio":                     map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回费归基金资产比例"},
	"fundestablishdate":                      map[string]interface{}{"type": "A", "size": 8, "comment": "基金成立日期YYYYMMDD"},
	"constantfee":                            map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "固定费用"},
	"isdiscount":                             map[string]interface{}{"type": "C", "size": 1, "comment": "1-是"},
	"buypayperiod":                           map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购交收天数"},
	"redemptionpayperiod":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "赎回交收天数"},
	"conversionpayperiod":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换交收天数"},
	"chargepaymethod":                        map[string]interface{}{"type": "C", "size": 1, "comment": "1-全额结算"},
	"compareproportion":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "相对比例"},
	"comparecapitaltype":                     map[string]interface{}{"type": "C", "size": 3, "comment": "相对资金类型"},
	"subpaybackperiod":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "认购退款交收天数"},
	"dividendpayperiod":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "分红交收天数"},
	"wholeflag":                              map[string]interface{}{"type": "C", "size": 1, "comment": "1-全量"},
	"modifyway":                              map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"changeagencyfee":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "转换代理费"},
	"recuperateagencyfee":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "补差代理费"},
	"redemptionsequence":                     map[string]interface{}{"type": "C", "size": 1, "comment": "1-后进先出"},
	"buyupperamount":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申购金额上限"},
	"covertinupperamount":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金转换转入金额上限"},
	"periodsubupperamount":                   map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "定时定额申购金额上限"},
	"periodsubtimeunit":                      map[string]interface{}{"type": "C", "size": 1, "comment": "定投周期单位"},
	"fundincome":                             map[string]interface{}{"type": "N", "size": 8, "scale": 5, "comment": "货币基金万份收益率"},
	"fundincomeflag":                         map[string]interface{}{"type": "C", "size": 1, "comment": "1-负"},
	"yield":                                  map[string]interface{}{"type": "N", "size": 8, "scale": 5, "comment": "货币基金七日年收益"},
	"yieldflag":                              map[string]interface{}{"type": "C", "size": 1, "comment": "1-负"},
	"guaranteednav":                          map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "保本净值"},
	"handlecharge":                           map[string]interface{}{"type": "N", "size": 10, "scale": 2, "comment": "经手费"},
	"undistributemonetaryincome":             map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "货币基金未付收益金额"},
	"guaranteedamount":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "剩余保本金额"},
	"exchangeflag":                           map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"undistributemonetaryincomeflag":         map[string]interface{}{"type": "C", "size": 1, "comment": "货币基金未付收益金额正负"},
	"ref":                                    map[string]interface{}{"type": "C", "size": 10, "comment": "券商用"},
	"internet":                               map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"sharetype":                              map[string]interface{}{"type": "C", "size": 1, "comment": "份额类别"},
	"nationality":                            map[string]interface{}{"type": "C", "size": 3, "comment": "投资者国籍"},
	"netno":                                  map[string]interface{}{"type": "C", "size": 9, "comment": "操作（清算）网点编号"},
	"targetsharetype":                        map[string]interface{}{"type": "C", "size": 1, "comment": "对方基金份额类别"},
	"sourcetype":                             map[string]interface{}{"type": "C", "size": 1, "comment": "2-定期定额申购3-分红"},
	"vastredeemratio":                        map[string]interface{}{"type": "N", "size": 9, "scale": 8, "comment": "巨额赎回兑现比例"},
	"broker":                                 map[string]interface{}{"type": "C", "size": 12, "comment": "经纪人"},
	"protocalenddate":                        map[string]interface{}{"type": "A", "size": 8, "comment": "协议截止日期"},
	"rationdate":                             map[string]interface{}{"type": "N", "size": 5, "scale": 0, "comment": "定期定额的指定日期"},
	"funddayincomeflag":                      map[string]interface{}{"type": "C", "size": 1, "comment": "基金当日总收益正负"},
	"funddayincome":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "基金当日总收益"},
	"customerid":                             map[string]interface{}{"type": "C", "size": 12, "comment": "客户号"},
	"rationkind":                             map[string]interface{}{"type": "C", "size": 3, "comment": "定期定额品种代码"},
	"belongfundassetfare":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "归基金资产费"},
	"backfare":                               map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "后收手续费"},
	"recuperatefee":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "补差费"},
	"changefee":                              map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "转换费"},
	"achievementpay":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "业绩报酬"},
	"achievementcompen":                      map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "业绩补偿"},
	"overamount":                             map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申请超限金额"},
	"overshares":                             map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "申请超限份额"},
	"capitalgaintax":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "红利所得税"},
	"cashdividendfee":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "现金分红手续费"},
	"confirmpaydate":                         map[string]interface{}{"type": "C", "size": 8, "comment": "确认支付日期"},
	"netvaluedate":                           map[string]interface{}{"type": "C", "size": 8, "comment": "净值日期"},
	"netvaluetype":                           map[string]interface{}{"type": "C", "size": 1, "comment": "2-赎回净值"},
	"fundyearincomerate":                     map[string]interface{}{"type": "N", "size": 8, "scale": 5, "comment": "货币基金年收益率"},
	"fundyearincomerateflag":                 map[string]interface{}{"type": "C", "size": 1, "comment": "货币基金年收益率正负"},
	"begininterestdate":                      map[string]interface{}{"type": "C", "size": 8, "comment": "起息日期"},
	"lofdatatype":                            map[string]interface{}{"type": "C", "size": 1, "comment": "LOF数据类别转发LOF认购明细中数据类别"},
	"managerrealratio":                       map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "实际计算折扣"},
	"costprice":                              map[string]interface{}{"type": "N", "size": 7, "scale": 4, "comment": "成本价"},
	"generaltaserialno":                      map[string]interface{}{"type": "A", "size": 20, "comment": "总TA确认流水号用于发送交易明细"},
	"drawbonusunit":                          map[string]interface{}{"type": "N", "size": 10, "scale": 0, "comment": "分红单位"},
	"frozensharesforreinvest":                map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "冻结再投资份额"},
	"sharesadjustmentflag":                   map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"periodicstatus":                         map[string]interface{}{"type": "C", "size": 1, "comment": "定期定额状态"},
	"transferagencystatus":                   map[string]interface{}{"type": "C", "size": 1, "comment": "转托管状态"},
	"transactionaccountstatus":               map[string]interface{}{"type": "C", "size": 1, "comment": ""},
	"rationno":                               map[string]interface{}{"type": "C", "size": 3, "comment": "定期定额序号"},
	"achievementpayflag":                     map[string]interface{}{"type": "C", "size": 1, "comment": "业绩报酬正负"},
	"indimaxpurchase":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人最大申购金额"},
	"instmaxpurchase":                        map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人最大申购金额"},
	"indidaymaxsumbuy":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人当日累计购买最大金额"},
	"instdaymaxsumbuy":                       map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人当日累计购买最大金额"},
	"indidaymaxsumredeem":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人当日累计赎回最大份额"},
	"instdaymaxsumredeem":                    map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人当日累计赎回最大份额"},
	"indimaxredeem":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "个人最大赎回份额"},
	"instmaxredeem":                          map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "法人最大赎回份额"},
	"targetregistrarcode":                    map[string]interface{}{"type": "C", "size": 2, "comment": "对方TA代码"},
	"acctnooffminclearingagency":             map[string]interface{}{"type": "C", "size": 28, "comment": "基金管理人在资金清算机构的交收账号"},
	"acctnameoffminclearingagency":           map[string]interface{}{"type": "C", "size": 60, "comment": "基金管理人在资金清算机构的交收账户名"},
	"chargetype":                             map[string]interface{}{"type": "C", "size": 1, "comment": "收费类型"},
	"specifyratefee":                         map[string]interface{}{"type": "N", "size": 9, "scale": 0, "comment": "指定费率"},
	"specifyfee":                             map[string]interface{}{"type": "N", "size": 16, "scale": 0, "comment": "指定费用"},
	"acceptplace":                            map[string]interface{}{"type": "C", "size": 40, "comment": "受理地点"},
	"cardno":                                 map[string]interface{}{"type": "C", "size": 32, "comment": "客户银行卡号或券商端资金账号"},
	"contracttype":                           map[string]interface{}{"type": "C", "size": 1, "comment": "合同类型"},
	"notes":                                  map[string]interface{}{"type": "C", "size": 64, "comment": "附加信息"},
	"reservedfield1":                         map[string]interface{}{"type": "C", "size": 20, "comment": "预留字段1"},
	"reservedfield2":                         map[string]interface{}{"type": "C", "size": 20, "comment": "预留字段2"},
	"reservedfield3":                         map[string]interface{}{"type": "C", "size": 30, "comment": "预留字段3"},
	"reservedfield4":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "预留字段4"},
	"reservedfield5":                         map[string]interface{}{"type": "N", "size": 16, "scale": 2, "comment": "预留字段5"},
	"riskmatching":                           map[string]interface{}{"type": "C", "size": 1, "comment": "风险承受能力匹配情况"},
	"seconddate":                             map[string]interface{}{"type": "C", "size": 8, "comment": "第二用途日期"},
	"secondnotes":                            map[string]interface{}{"type": "C", "size": 64, "comment": "第二用途信息"},
	"secondstatus":                           map[string]interface{}{"type": "C", "size": 1, "comment": "第二用途状态"},
	"serialno":                               map[string]interface{}{"type": "C", "size": 26, "comment": "流水号"},
	"signrisknotice":                         map[string]interface{}{"type": "C", "size": 1, "comment": "已签署风险揭示书"},
	"signtype":                               map[string]interface{}{"type": "C", "size": 1, "comment": "签署类型"},
	"thirddate":                              map[string]interface{}{"type": "C", "size": 8, "comment": "第三用途日期"},
	"thirdnotes":                             map[string]interface{}{"type": "C", "size": 64, "comment": "第三用途信息"},
	"thirdstatus":                            map[string]interface{}{"type": "C", "size": 1, "comment": "第三用途状态"},
	"version":                                map[string]interface{}{"type": "C", "size": 3, "comment": "版本号"},
	"aggregationoftransactionbybusinesstype": map[string]interface{}{"type": "N", "size": 8, "scale": 0, "comment": "每种业务笔数汇总"},
	"allowredemptdate":                       map[string]interface{}{"type": "A", "size": 8, "comment": "可赎回日期"},
}
